# Generated by Django 4.1.7 on 2023-03-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dis_ID', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('Disaster_Group', models.TextField()),
                ('Disaster_Type', models.TextField()),
                ('Country', models.TextField()),
                ('ISO', models.TextField()),
                ('Total_Affected', models.TextField()),
            ],
        ),
    ]
