# Generated by Django 4.1.7 on 2023-03-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='Total_Damages',
            field=models.TextField(default='0', max_length=100),
        ),
    ]
