# Generated by Django 4.1.7 on 2023-03-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_table', '0003_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Total_Damages_usd',
            field=models.DateTimeField(default='0', max_length=100),
        ),
    ]
