# Generated by Django 4.1.7 on 2023-03-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_table', '0005_details_disaster_subsubtype_alter_details_cpi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='CPI',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='summary',
            name='Total_Damages',
            field=models.TextField(),
        ),
    ]
