# Generated by Django 4.1.2 on 2023-03-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_table', '0006_alter_details_cpi_alter_summary_total_damages'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='is_delete',
            field=models.IntegerField(default=0),
        ),
    ]
