# Generated by Django 4.1.2 on 2023-03-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'disaster_message',
            },
        ),
    ]
